### ISSUE TITLE
Crashes on F5

### ISSUE THREAD

**Issue by TheIgnorantDev** [44697665727365/DarkAndDarkerRewrite#1]
When pressing F5 the application crashes
`if (uMsg == WM_KEYUP && wParam == VK_F5)
{
	RenderMenu = !RenderMenu;
	ImGui::GetIO().MouseDrawCursor = RenderMenu;
	return 0;
}`
it appears that it renders the menu.

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION writing address 0x0000000000000070

**Comment by MrMyBaa** [comment]
Hello! Appreciate you very much! Can I have your contact information?

**Comment by JARN98** [comment]
same problem here!! :D
